var types = [
  [
    {
      "10,000,000 Volt Thunderbolt": "special",
      "Absorb": "special",
      "Accelerock": "physical",
      "Acid": "special",
      "Acid Armor": "status",
      "Acid Downpour": "",
      "Acid Spray": "special",
      "Acrobatics": "physical",
      "Acupressure": "status",
      "Aerial Ace": "physical",
      "Aeroblast": "special",
      "After You": "status",
      "Agility": "status",
      "Air Cutter": "special",
      "Air Slash": "special",
      "All-Out Pummeling": "",
      "Ally Switch": "status",
      "Amnesia": "status",
      "Anchor Shot": "physical",
      "Ancient Power": "special",
      "Aqua Jet": "physical",
      "Aqua Ring": "status",
      "Aqua Tail": "physical",
      "Arm Thrust": "physical",
      "Aromatherapy": "status",
      "Aromatic Mist": "status",
      "Assist": "status",
      "Assurance": "physical",
      "Astonish": "physical",
      "Attack Order": "physical",
      "Attract": "status",
      "Aura Sphere": "special",
      "Aurora Beam": "special",
      "Aurora Veil": "status",
      "Autotomize": "status",
      "Avalanche": "physical",
      "Baby-Doll Eyes": "status",
      "Baddy Bad": "special",
      "Baneful Bunker": "status",
      "Barrage": "physical",
      "Barrier": "status",
      "Baton Pass": "status",
      "Beak Blast": "physical",
      "Beat Up": "physical",
      "Belch": "special",
      "Belly Drum": "status",
      "Bestow": "status",
      "Bide": "physical",
      "Bind": "physical",
      "Bite": "physical",
      "Black Hole Eclipse": "",
      "Blast Burn": "special",
      "Blaze Kick": "physical",
      "Blizzard": "special",
      "Block": "status",
      "Bloom Doom": "",
      "Blue Flare": "special",
      "Body Slam": "physical",
      "Bolt Strike": "physical",
      "Bone Club": "physical",
      "Bone Rush": "physical",
      "Bonemerang": "physical",
      "Boomburst": "special",
      "Bounce": "physical",
      "Bouncy Bubble": "special",
      "Brave Bird": "physical",
      "Breakneck Blitz": "",
      "Brick Break": "physical",
      "Brine": "special",
      "Brutal Swing": "physical",
      "Bubble": "special",
      "Bubble Beam": "special",
      "Bug Bite": "physical",
      "Bug Buzz": "special",
      "Bulk Up": "status",
      "Bulldoze": "physical",
      "Bullet Punch": "physical",
      "Bullet Seed": "physical",
      "Burn Up": "special",
      "Buzzy Buzz": "special",
      "Calm Mind": "status",
      "Camouflage": "status",
      "Captivate": "status",
      "Catastropika": "physical",
      "Celebrate": "status",
      "Charge": "status",
      "Charge Beam": "special",
      "Charm": "status",
      "Chatter": "special",
      "Chip Away": "physical",
      "Circle Throw": "physical",
      "Clamp": "physical",
      "Clanging Scales": "special",
      "Clangorous Soulblaze": "special",
      "Clear Smog": "special",
      "Close Combat": "physical",
      "Coil": "status",
      "Comet Punch": "physical",
      "Confide": "status",
      "Confuse Ray": "status",
      "Confusion": "special",
      "Constrict": "physical",
      "Continental Crush": "",
      "Conversion": "status",
      "Conversion 2": "status",
      "Copycat": "status",
      "Core Enforcer": "special",
      "Corkscrew Crash": "",
      "Cosmic Power": "status",
      "Cotton Guard": "status",
      "Cotton Spore": "status",
      "Counter": "physical",
      "Covet": "physical",
      "Crabhammer": "physical",
      "Crafty Shield": "status",
      "Cross Chop": "physical",
      "Cross Poison": "physical",
      "Crunch": "physical",
      "Crush Claw": "physical",
      "Crush Grip": "physical",
      "Curse": "status",
      "Cut": "physical",
      "Dark Pulse": "special",
      "Dark Void": "status",
      "Darkest Lariat": "physical",
      "Dazzling Gleam": "special",
      "Defend Order": "status",
      "Defense Curl": "status",
      "Defog": "status",
      "Destiny Bond": "status",
      "Detect": "status",
      "Devastating Drake": "",
      "Diamond Storm": "physical",
      "Dig": "physical",
      "Disable": "status",
      "Disarming Voice": "special",
      "Discharge": "special",
      "Dive": "physical",
      "Dizzy Punch": "physical",
      "Doom Desire": "special",
      "Double Hit": "physical",
      "Double Iron Bash": "physical",
      "Double Kick": "physical",
      "Double Slap": "physical",
      "Double Team": "status",
      "Double-Edge": "physical",
      "Draco Meteor": "special",
      "Dragon Ascent": "physical",
      "Dragon Breath": "special",
      "Dragon Claw": "physical",
      "Dragon Dance": "status",
      "Dragon Hammer": "physical",
      "Dragon Pulse": "special",
      "Dragon Rage": "special",
      "Dragon Rush": "physical",
      "Dragon Tail": "physical",
      "Drain Punch": "physical",
      "Draining Kiss": "special",
      "Dream Eater": "special",
      "Drill Peck": "physical",
      "Drill Run": "physical",
      "Dual Chop": "physical",
      "Dynamic Punch": "physical",
      "Earth Power": "special",
      "Earthquake": "physical",
      "Echoed Voice": "special",
      "Eerie Impulse": "status",
      "Egg Bomb": "physical",
      "Electric Terrain": "status",
      "Electrify": "status",
      "Electro Ball": "special",
      "Electroweb": "special",
      "Embargo": "status",
      "Ember": "special",
      "Encore": "status",
      "Endeavor": "physical",
      "Endure": "status",
      "Energy Ball": "special",
      "Entrainment": "status",
      "Eruption": "special",
      "Explosion": "physical",
      "Extrasensory": "special",
      "Extreme Evoboost": "status",
      "Extreme Speed": "physical",
      "Facade": "physical",
      "Fairy Lock": "status",
      "Fairy Wind": "special",
      "Fake Out": "physical",
      "Fake Tears": "status",
      "False Swipe": "physical",
      "Feather Dance": "status",
      "Feint": "physical",
      "Feint Attack": "physical",
      "Fell Stinger": "physical",
      "Fiery Dance": "special",
      "Final Gambit": "special",
      "Fire Blast": "special",
      "Fire Fang": "physical",
      "Fire Lash": "physical",
      "Fire Pledge": "special",
      "Fire Punch": "physical",
      "Fire Spin": "special",
      "First Impression": "physical",
      "Fissure": "physical",
      "Flail": "physical",
      "Flame Burst": "special",
      "Flame Charge": "physical",
      "Flame Wheel": "physical",
      "Flamethrower": "special",
      "Flare Blitz": "physical",
      "Flash": "status",
      "Flash Cannon": "special",
      "Flatter": "status",
      "Fleur Cannon": "special",
      "Fling": "physical",
      "Floaty Fall": "physical",
      "Floral Healing": "status",
      "Flower Shield": "status",
      "Fly": "physical",
      "Flying Press": "physical",
      "Focus Blast": "special",
      "Focus Energy": "status",
      "Focus Punch": "physical",
      "Follow Me": "status",
      "Force Palm": "physical",
      "Foresight": "status",
      "Forest's Curse": "status",
      "Foul Play": "physical",
      "Freeze Shock": "physical",
      "Freeze-Dry": "special",
      "Freezy Frost": "special",
      "Frenzy Plant": "special",
      "Frost Breath": "special",
      "Frustration": "physical",
      "Fury Attack": "physical",
      "Fury Cutter": "physical",
      "Fury Swipes": "physical",
      "Fusion Bolt": "physical",
      "Fusion Flare": "special",
      "Future Sight": "special",
      "Gastro Acid": "status",
      "Gear Grind": "physical",
      "Gear Up": "status",
      "Genesis Supernova": "special",
      "Geomancy": "status",
      "Giga Drain": "special",
      "Giga Impact": "physical",
      "Gigavolt Havoc": "",
      "Glaciate": "special",
      "Glare": "status",
      "Glitzy Glow": "special",
      "Grass Knot": "special",
      "Grass Pledge": "special",
      "Grass Whistle": "status",
      "Grassy Terrain": "status",
      "Gravity": "status",
      "Growl": "status",
      "Growth": "status",
      "Grudge": "status",
      "Guard Split": "status",
      "Guard Swap": "status",
      "Guardian of Alola": "special",
      "Guillotine": "physical",
      "Gunk Shot": "physical",
      "Gust": "special",
      "Gyro Ball": "physical",
      "Hail": "status",
      "Hammer Arm": "physical",
      "Happy Hour": "status",
      "Harden": "status",
      "Haze": "status",
      "Head Charge": "physical",
      "Head Smash": "physical",
      "Headbutt": "physical",
      "Heal Bell": "status",
      "Heal Block": "status",
      "Heal Order": "status",
      "Heal Pulse": "status",
      "Healing Wish": "status",
      "Heart Stamp": "physical",
      "Heart Swap": "status",
      "Heat Crash": "physical",
      "Heat Wave": "special",
      "Heavy Slam": "physical",
      "Helping Hand": "status",
      "Hex": "special",
      "Hidden Power": "special",
      "High Horsepower": "physical",
      "High Jump Kick": "physical",
      "Hold Back": "physical",
      "Hold Hands": "status",
      "Hone Claws": "status",
      "Horn Attack": "physical",
      "Horn Drill": "physical",
      "Horn Leech": "physical",
      "Howl": "status",
      "Hurricane": "special",
      "Hydro Cannon": "special",
      "Hydro Pump": "special",
      "Hydro Vortex": "",
      "Hyper Beam": "special",
      "Hyper Fang": "physical",
      "Hyper Voice": "special",
      "Hyperspace Fury": "physical",
      "Hyperspace Hole": "special",
      "Hypnosis": "status",
      "Ice Ball": "physical",
      "Ice Beam": "special",
      "Ice Burn": "special",
      "Ice Fang": "physical",
      "Ice Hammer": "physical",
      "Ice Punch": "physical",
      "Ice Shard": "physical",
      "Icicle Crash": "physical",
      "Icicle Spear": "physical",
      "Icy Wind": "special",
      "Imprison": "status",
      "Incinerate": "special",
      "Inferno": "special",
      "Inferno Overdrive": "",
      "Infestation": "special",
      "Ingrain": "status",
      "Instruct": "status",
      "Ion Deluge": "status",
      "Iron Defense": "status",
      "Iron Head": "physical",
      "Iron Tail": "physical",
      "Judgment": "special",
      "Jump Kick": "physical",
      "Karate Chop": "physical",
      "Kinesis": "status",
      "King's Shield": "status",
      "Knock Off": "physical",
      "Land's Wrath": "physical",
      "Laser Focus": "status",
      "Last Resort": "physical",
      "Lava Plume": "special",
      "Leaf Blade": "physical",
      "Leaf Storm": "special",
      "Leaf Tornado": "special",
      "Leafage": "physical",
      "Leech Life": "physical",
      "Leech Seed": "status",
      "Leer": "status",
      "Let's Snuggle Forever": "physical",
      "Lick": "physical",
      "Light of Ruin": "special",
      "Light Screen": "status",
      "Light That Burns the Sky": "special",
      "Liquidation": "physical",
      "Lock-On": "status",
      "Lovely Kiss": "status",
      "Low Kick": "physical",
      "Low Sweep": "physical",
      "Lucky Chant": "status",
      "Lunar Dance": "status",
      "Lunge": "physical",
      "Luster Purge": "special",
      "Mach Punch": "physical",
      "Magic Coat": "status",
      "Magic Room": "status",
      "Magical Leaf": "special",
      "Magma Storm": "special",
      "Magnet Bomb": "physical",
      "Magnet Rise": "status",
      "Magnetic Flux": "status",
      "Magnitude": "physical",
      "Malicious Moonsault": "physical",
      "Mat Block": "status",
      "Me First": "status",
      "Mean Look": "status",
      "Meditate": "status",
      "Mega Drain": "special",
      "Mega Kick": "physical",
      "Mega Punch": "physical",
      "Megahorn": "physical",
      "Memento": "status",
      "Menacing Moonraze Maelstrom": "special",
      "Metal Burst": "physical",
      "Metal Claw": "physical",
      "Metal Sound": "status",
      "Meteor Mash": "physical",
      "Metronome": "status",
      "Milk Drink": "status",
      "Mimic": "status",
      "Mind Blown": "special",
      "Mind Reader": "status",
      "Minimize": "status",
      "Miracle Eye": "status",
      "Mirror Coat": "special",
      "Mirror Move": "status",
      "Mirror Shot": "special",
      "Mist": "status",
      "Mist Ball": "special",
      "Misty Terrain": "status",
      "Moonblast": "special",
      "Moongeist Beam": "special",
      "Moonlight": "status",
      "Morning Sun": "status",
      "Mud Bomb": "special",
      "Mud Shot": "special",
      "Mud Sport": "status",
      "Mud-Slap": "special",
      "Muddy Water": "special",
      "Multi-Attack": "physical",
      "Mystical Fire": "special",
      "Nasty Plot": "status",
      "Natural Gift": "physical",
      "Nature Power": "status",
      "Nature's Madness": "special",
      "Needle Arm": "physical",
      "Never-Ending Nightmare": "",
      "Night Daze": "special",
      "Night Shade": "special",
      "Night Slash": "physical",
      "Nightmare": "status",
      "Noble Roar": "status",
      "Nuzzle": "physical",
      "Oblivion Wing": "special",
      "Oceanic Operetta": "special",
      "Octazooka": "special",
      "Odor Sleuth": "status",
      "Ominous Wind": "special",
      "Origin Pulse": "special",
      "Outrage": "physical",
      "Overheat": "special",
      "Pain Split": "status",
      "Parabolic Charge": "special",
      "Parting Shot": "status",
      "Pay Day": "physical",
      "Payback": "physical",
      "Peck": "physical",
      "Perish Song": "status",
      "Petal Blizzard": "physical",
      "Petal Dance": "special",
      "Phantom Force": "physical",
      "Photon Geyser": "special",
      "Pika Papow": "special",
      "Pin Missile": "physical",
      "Plasma Fists": "physical",
      "Play Nice": "status",
      "Play Rough": "physical",
      "Pluck": "physical",
      "Poison Fang": "physical",
      "Poison Gas": "status",
      "Poison Jab": "physical",
      "Poison Powder": "status",
      "Poison Sting": "physical",
      "Poison Tail": "physical",
      "Pollen Puff": "special",
      "Pound": "physical",
      "Powder": "status",
      "Powder Snow": "special",
      "Power Gem": "special",
      "Power Split": "status",
      "Power Swap": "status",
      "Power Trick": "status",
      "Power Trip": "physical",
      "Power Whip": "physical",
      "Power-Up Punch": "physical",
      "Precipice Blades": "physical",
      "Present": "physical",
      "Prismatic Laser": "special",
      "Protect": "status",
      "Psybeam": "special",
      "Psych Up": "status",
      "Psychic": "special",
      "Psychic Fangs": "physical",
      "Psychic Terrain": "status",
      "Psycho Boost": "special",
      "Psycho Cut": "physical",
      "Psycho Shift": "status",
      "Psyshock": "special",
      "Psystrike": "special",
      "Psywave": "special",
      "Pulverizing Pancake": "physical",
      "Punishment": "physical",
      "Purify": "status",
      "Pursuit": "physical",
      "Quash": "status",
      "Quick Attack": "physical",
      "Quick Guard": "status",
      "Quiver Dance": "status",
      "Rage": "physical",
      "Rage Powder": "status",
      "Rain Dance": "status",
      "Rapid Spin": "physical",
      "Razor Leaf": "physical",
      "Razor Shell": "physical",
      "Razor Wind": "special",
      "Recover": "status",
      "Recycle": "status",
      "Reflect": "status",
      "Reflect Type": "status",
      "Refresh": "status",
      "Relic Song": "special",
      "Rest": "status",
      "Retaliate": "physical",
      "Return": "physical",
      "Revelation Dance": "special",
      "Revenge": "physical",
      "Reversal": "physical",
      "Roar": "status",
      "Roar of Time": "special",
      "Rock Blast": "physical",
      "Rock Climb": "physical",
      "Rock Polish": "status",
      "Rock Slide": "physical",
      "Rock Smash": "physical",
      "Rock Throw": "physical",
      "Rock Tomb": "physical",
      "Rock Wrecker": "physical",
      "Role Play": "status",
      "Rolling Kick": "physical",
      "Rollout": "physical",
      "Roost": "status",
      "Rototiller": "status",
      "Round": "special",
      "Sacred Fire": "physical",
      "Sacred Sword": "physical",
      "Safeguard": "status",
      "Sand Attack": "status",
      "Sand Tomb": "physical",
      "Sandstorm": "status",
      "Sappy Seed": "physical",
      "Savage Spin-Out": "",
      "Scald": "special",
      "Scary Face": "status",
      "Scratch": "physical",
      "Screech": "status",
      "Searing Shot": "special",
      "Searing Sunraze Smash": "physical",
      "Secret Power": "physical",
      "Secret Sword": "special",
      "Seed Bomb": "physical",
      "Seed Flare": "special",
      "Seismic Toss": "physical",
      "Self-Destruct": "physical",
      "Shadow Ball": "special",
      "Shadow Bone": "physical",
      "Shadow Claw": "physical",
      "Shadow Force": "physical",
      "Shadow Punch": "physical",
      "Shadow Sneak": "physical",
      "Sharpen": "status",
      "Shattered Psyche": "",
      "Sheer Cold": "special",
      "Shell Smash": "status",
      "Shell Trap": "special",
      "Shift Gear": "status",
      "Shock Wave": "special",
      "Shore Up": "status",
      "Signal Beam": "special",
      "Silver Wind": "special",
      "Simple Beam": "status",
      "Sing": "status",
      "Sinister Arrow Raid": "physical",
      "Sizzly Slide": "physical",
      "Sketch": "status",
      "Skill Swap": "status",
      "Skull Bash": "physical",
      "Sky Attack": "physical",
      "Sky Drop": "physical",
      "Sky Uppercut": "physical",
      "Slack Off": "status",
      "Slam": "physical",
      "Slash": "physical",
      "Sleep Powder": "status",
      "Sleep Talk": "status",
      "Sludge": "special",
      "Sludge Bomb": "special",
      "Sludge Wave": "special",
      "Smack Down": "physical",
      "Smart Strike": "physical",
      "Smelling Salts": "physical",
      "Smog": "special",
      "Smokescreen": "status",
      "Snarl": "special",
      "Snatch": "status",
      "Snore": "special",
      "Soak": "status",
      "Soft-Boiled": "status",
      "Solar Beam": "special",
      "Solar Blade": "physical",
      "Sonic Boom": "special",
      "Soul-Stealing 7-Star Strike": "physical",
      "Spacial Rend": "special",
      "Spark": "physical",
      "Sparkling Aria": "special",
      "Sparkly Swirl": "special",
      "Spectral Thief": "physical",
      "Speed Swap": "status",
      "Spider Web": "status",
      "Spike Cannon": "physical",
      "Spikes": "status",
      "Spiky Shield": "status",
      "Spirit Shackle": "physical",
      "Spit Up": "special",
      "Spite": "status",
      "Splash": "status",
      "Splintered Stormshards": "physical",
      "Splishy Splash": "special",
      "Spore": "status",
      "Spotlight": "status",
      "Stealth Rock": "status",
      "Steam Eruption": "special",
      "Steamroller": "physical",
      "Steel Wing": "physical",
      "Sticky Web": "status",
      "Stockpile": "status",
      "Stoked Sparksurfer": "special",
      "Stomp": "physical",
      "Stomping Tantrum": "physical",
      "Stone Edge": "physical",
      "Stored Power": "special",
      "Storm Throw": "physical",
      "Strength": "physical",
      "Strength Sap": "status",
      "String Shot": "status",
      "Struggle": "physical",
      "Struggle Bug": "special",
      "Stun Spore": "status",
      "Submission": "physical",
      "Substitute": "status",
      "Subzero Slammer": "",
      "Sucker Punch": "physical",
      "Sunny Day": "status",
      "Sunsteel Strike": "physical",
      "Super Fang": "physical",
      "Superpower": "physical",
      "Supersonic": "status",
      "Supersonic Skystrike": "",
      "Surf": "special",
      "Swagger": "status",
      "Swallow": "status",
      "Sweet Kiss": "status",
      "Sweet Scent": "status",
      "Swift": "special",
      "Switcheroo": "status",
      "Swords Dance": "status",
      "Synchronoise": "special",
      "Synthesis": "status",
      "Tackle": "physical",
      "Tail Glow": "status",
      "Tail Slap": "physical",
      "Tail Whip": "status",
      "Tailwind": "status",
      "Take Down": "physical",
      "Taunt": "status",
      "Tearful Look": "status",
      "Techno Blast": "special",
      "Tectonic Rage": "",
      "Teeter Dance": "status",
      "Telekinesis": "status",
      "Teleport": "status",
      "Thief": "physical",
      "Thousand Arrows": "physical",
      "Thousand Waves": "physical",
      "Thrash": "physical",
      "Throat Chop": "physical",
      "Thunder": "special",
      "Thunder Fang": "physical",
      "Thunder Punch": "physical",
      "Thunder Shock": "special",
      "Thunder Wave": "status",
      "Thunderbolt": "special",
      "Tickle": "status",
      "Topsy-Turvy": "status",
      "Torment": "status",
      "Toxic": "status",
      "Toxic Spikes": "status",
      "Toxic Thread": "status",
      "Transform": "status",
      "Tri Attack": "special",
      "Trick": "status",
      "Trick Room": "status",
      "Trick-or-Treat": "status",
      "Triple Kick": "physical",
      "Trop Kick": "physical",
      "Trump Card": "special",
      "Twineedle": "physical",
      "Twinkle Tackle": "",
      "Twister": "special",
      "U-turn": "physical",
      "Uproar": "special",
      "V-create": "physical",
      "Vacuum Wave": "special",
      "Veevee Volley": "physical",
      "Venom Drench": "status",
      "Venoshock": "special",
      "Vice Grip": "physical",
      "Vine Whip": "physical",
      "Vital Throw": "physical",
      "Volt Switch": "special",
      "Volt Tackle": "physical",
      "Wake-Up Slap": "physical",
      "Water Gun": "special",
      "Water Pledge": "special",
      "Water Pulse": "special",
      "Water Shuriken": "special",
      "Water Sport": "status",
      "Water Spout": "special",
      "Waterfall": "physical",
      "Weather Ball": "special",
      "Whirlpool": "special",
      "Whirlwind": "status",
      "Wide Guard": "status",
      "Wild Charge": "physical",
      "Will-O-Wisp": "status",
      "Wing Attack": "physical",
      "Wish": "status",
      "Withdraw": "status",
      "Wonder Room": "status",
      "Wood Hammer": "physical",
      "Work Up": "status",
      "Worry Seed": "status",
      "Wrap": "physical",
      "Wring Out": "special",
      "X-Scissor": "physical",
      "Yawn": "status",
      "Zap Cannon": "special",
      "Zen Headbutt": "physical",
      "Zing Zap": "physical",
      "Zippy Zap": "physical"
    }
  ]
]

module.exports = {types:types}
